"""add disruptions agent_runs operator_results policy_evaluations workbench_items

Revision ID: 0239f3f980a3
Revises: c3d4e5f6g7h8
Create Date: 2026-08-07 07:18:08.914437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0239f3f980a3'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruptions_external_id'), 'disruptions', ['external_id'], unique=True)
    op.create_index(op.f('ix_disruptions_id'), 'disruptions', ['id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disruption_id', sa.Integer(), nullable=True),
    sa.Column('supervity_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_disruption_id'), 'agent_runs', ['disruption_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_supervity_run_id'), 'agent_runs', ['supervity_run_id'], unique=False)
    op.create_table('operator_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_results_agent_run_id'), 'operator_results', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_operator_results_id'), 'operator_results', ['id'], unique=False)
    op.create_index(op.f('ix_operator_results_operator_name'), 'operator_results', ['operator_name'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('policy_name', sa.String(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluations_agent_run_id'), 'policy_evaluations', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_id'), 'policy_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_policy_name'), 'policy_evaluations', ['policy_name'], unique=False)
    op.create_table('workbench_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decision_notes', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workbench_items_agent_run_id'), 'workbench_items', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_workbench_items_id'), 'workbench_items', ['id'], unique=False)
    op.create_index(op.f('ix_workbench_items_status'), 'workbench_items', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_workbench_items_status'), table_name='workbench_items')
    op.drop_index(op.f('ix_workbench_items_id'), table_name='workbench_items')
    op.drop_index(op.f('ix_workbench_items_agent_run_id'), table_name='workbench_items')
    op.drop_table('workbench_items')
    op.drop_index(op.f('ix_policy_evaluations_policy_name'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_agent_run_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_operator_results_operator_name'), table_name='operator_results')
    op.drop_index(op.f('ix_operator_results_id'), table_name='operator_results')
    op.drop_index(op.f('ix_operator_results_agent_run_id'), table_name='operator_results')
    op.drop_table('operator_results')
    op.drop_index(op.f('ix_agent_runs_supervity_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_disruption_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_disruptions_id'), table_name='disruptions')
    op.drop_index(op.f('ix_disruptions_external_id'), table_name='disruptions')
    op.drop_table('disruptions')
    # ### end Alembic commands ###
